eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070

spring:
  application:
    name: school
  datasource:
    # url: ${Spring.dataSource.url}
    # username: ${Spring.dataSource.username}
    # password: ${Spring.dataSource.password}
    url: jdbc:postgresql://localhost:5432/schools
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8222/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0