eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
  
spring:
  application:
    name: student
  datasource:
    # url: ${Spring.dataSource.url}
    # username: ${Spring.dataSource.username}
    # password: ${Spring.dataSource.password}
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  tracing:
    sampling:
      probability: 1.0